# -*- coding: utf-8 -*-
"""Arts and Advanced Big Data - Kim-Week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JH39h1gXg9vu3GHBGQ2e7RvAUvEjpmD_

# Mini project A
"""

# Mini Project A: Generative Poster
# Author: Kim Seyeon
# Course: Arts and Advanced Big Data
# Week 2 - Generative Poster Project

import matplotlib.pyplot as plt
import numpy as np
import random

# 1️⃣ 랜덤 파스텔 팔레트 생성 함수
def random_pastel_color():
    base = np.array([random.random() for _ in range(3)])
    return tuple(0.7 + 0.3 * base)  # 부드럽고 밝은 톤

def generate_palette(n=8):
    return [random_pastel_color() for _ in range(n)]

# 2️⃣ 블롭(유기적 곡선) 생성 함수
def generate_blob(n_points=100, radius=1.0, wobble=0.3, seed=None):
    if seed is not None:
        np.random.seed(seed)
    angles = np.linspace(0, 2*np.pi, n_points)
    radii = radius + np.random.uniform(-wobble, wobble, size=n_points)
    x = radii * np.cos(angles)
    y = radii * np.sin(angles)
    return x, y

# 3️⃣ 메인 포스터 생성 함수
def generate_poster(seed=None, n_layers=8, wobble_min=0.1, wobble_max=0.4, save=False):
    if seed is not None:
        random.seed(seed)
        np.random.seed(seed)

    plt.figure(figsize=(6, 8))
    plt.axis('off')
    plt.gca().set_facecolor((0.98, 0.97, 0.95))  # 오프화이트 배경

    palette = generate_palette(n_layers)
    for i in range(n_layers):
        wobble = random.uniform(wobble_min, wobble_max)
        radius = 1.2 - i * 0.08
        x, y = generate_blob(radius=radius, wobble=wobble)
        color = palette[i % len(palette)]
        plt.fill(x, y, color=color, alpha=0.4 + i*0.05)

    if save:
        plt.savefig("generative_poster.png", dpi=300, bbox_inches='tight')
    plt.show()

# 4️⃣ 실행
generate_poster(seed=42, n_layers=10)