# -*- coding: utf-8 -*-
"""Arts and Advanced Big Data-Kim-Week5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmGrnwhpvtuB-sWanjadlgooN6Rkq-gN

# Week 5 – CSV Palette Manager + Interactive Poster
Arts & Advanced Big Data

**Goal:** Manage a color palette in CSV (CRUD) and use it in an interactive generative poster.

## Step 1: Setup and Blob Function
"""

import random, math
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import hsv_to_rgb
import ipywidgets as widgets
from ipywidgets import interact
import pandas as pd
import os

# Blob shape
def blob(center=(0.5, 0.5), r=0.3, points=200, wobble=0.15):
    angles = np.linspace(0, 2*math.pi, points, endpoint=False)
    radii  = r * (1 + wobble*(np.random.rand(points)-0.5))
    x = center[0] + radii * np.cos(angles)
    y = center[1] + radii * np.sin(angles)
    return x, y

"""## Step 2: Palette Manager (CSV CRUD)
Functions to add, update, delete, and view colors in a CSV file.
"""

PALETTE_FILE = "palette.csv"

# Initialize palette.csv if not exists
if not os.path.exists(PALETTE_FILE):
    df_init = pd.DataFrame([
        {"name":"sky", "r":0.4, "g":0.7, "b":1.0},
        {"name":"sun", "r":1.0, "g":0.8, "b":0.2},
        {"name":"forest", "r":0.2, "g":0.6, "b":0.3}
    ])
    df_init.to_csv(PALETTE_FILE, index=False)

def read_palette():
    return pd.read_csv(PALETTE_FILE)

def add_color(name, r, g, b):
    df = read_palette()
    df = pd.concat([df, pd.DataFrame([{"name":name,"r":r,"g":g,"b":b}])], ignore_index=True)
    df.to_csv(PALETTE_FILE, index=False)
    print(f"Added {name}")

def update_color(name, r=None, g=None, b=None):
    df = read_palette()
    if name in df["name"].values:
        idx = df.index[df["name"]==name][0]
        if r is not None: df.at[idx,"r"] = r
        if g is not None: df.at[idx,"g"] = g
        if b is not None: df.at[idx,"b"] = b
        df.to_csv(PALETTE_FILE, index=False)
        print(f"Updated {name}")
    else:
        print(f"{name} not found")

def delete_color(name):
    df = read_palette()
    df = df[df["name"]!=name]
    df.to_csv(PALETTE_FILE, index=False)
    print(f"Deleted {name}")

"""## Step 3: Load Palette from CSV"""

def load_csv_palette():
    df = read_palette()
    return [(row.r, row.g, row.b) for row in df.itertuples()]

palette_csv = load_csv_palette()
print("Loaded palette:", palette_csv)

"""# Step 4: Visualize Palette"""

import matplotlib.pyplot as plt

def show_palette(palette):
    plt.figure(figsize=(6,2))
    for i, c in enumerate(palette):
        plt.fill_between([i, i+1], 0, 1, color=c)
        plt.text(i+0.5, -0.1, f"{i+1}", ha="center", va="top")
    plt.axis("off")
    plt.show()

# Show the loaded CSV palette
show_palette(palette_csv)

"""# Step 5: Palette Generator (Pastel, Vivid, Mono, Random, CSV)"""

def make_palette(k=6, mode="pastel", base_h=0.60):
    cols = []
    if mode == "csv":
        return load_csv_palette()

    for _ in range(k):
        if mode == "pastel":
            h = random.random(); s = random.uniform(0.15,0.35); v = random.uniform(0.9,1.0)
        elif mode == "vivid":
            h = random.random(); s = random.uniform(0.8,1.0);  v = random.uniform(0.8,1.0)
        elif mode == "mono":
            h = base_h;         s = random.uniform(0.2,0.6);   v = random.uniform(0.5,1.0)
        else: # random
            h = random.random(); s = random.uniform(0.3,1.0); v = random.uniform(0.5,1.0)
        cols.append(tuple(hsv_to_rgb([h,s,v])))
    return cols

"""# Step 6: Poster Drawing Function"""

def draw_poster(n_layers=8, wobble=0.15, palette_mode="pastel", seed=0):
    random.seed(seed); np.random.seed(seed)
    fig, ax = plt.subplots(figsize=(6,8))
    ax.axis('off')
    ax.set_facecolor((0.97,0.97,0.97))

    palette = make_palette(6, mode=palette_mode)
    for _ in range(n_layers):
        cx, cy = random.random(), random.random()
        rr = random.uniform(0.15, 0.45)
        x, y = blob((cx,cy), r=rr, wobble=wobble)
        color = random.choice(palette)
        alpha = random.uniform(0.3, 0.6)
        ax.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

    ax.text(0.05, 0.95, f"Interactive Poster • {palette_mode}",
            transform=ax.transAxes, fontsize=12, weight="bold")
    plt.show()

"""# Step 7: Interactive UI with CSV option"""

interact(
    draw_poster,
    n_layers=widgets.IntSlider(min=3,max=20,step=1,value=8, description="Layers"),
    wobble=widgets.FloatSlider(min=0.01,max=9.0,step=0.01,value=0.15, description="Wobble"),
    palette_mode=widgets.Dropdown(options=["pastel","vivid","mono","random","csv"], value="pastel"),
    seed=widgets.IntSlider(min=0,max=9999,step=1,value=0, description="Seed")
);

"""
# Create Your Own Palette
- Open `palette.csv`  
- Add at least **20 colors** with names and RGB values (0.0–1.0 scale)  
- Example:  
  ```csv
  name,r,g,b
  ocean,0.1,0.3,0.8
  sand,0.9,0.8,0.5
  sunset,0.9,0.4,0.3
  forest,0.2,0.6,0.3
  cloud,0.9,0.9,0.95
  ```

"""

add_color(name='koo', r=0.5, g=0.5, b=0.5)

delete_color(name='forest')

import pandas as pd

# 이미 있던 5개 색상 포함, 새로 추가한 15개 색상까지 총 20개
palette_data = [
    {"name":"ocean", "r":0.1, "g":0.3, "b":0.8},
    {"name":"sand", "r":0.9, "g":0.8, "b":0.5},
    {"name":"sunset", "r":0.9, "g":0.4, "b":0.3},
    {"name":"forest", "r":0.2, "g":0.6, "b":0.3},
    {"name":"cloud", "r":0.9, "g":0.9, "b":0.95},
    {"name":"lavender", "r":0.7, "g":0.5, "b":0.9},
    {"name":"rose", "r":0.9, "g":0.3, "b":0.5},
    {"name":"mint", "r":0.3, "g":0.9, "b":0.7},
    {"name":"gold", "r":1.0, "g":0.84, "b":0.0},
    {"name":"sky", "r":0.4, "g":0.7, "b":1.0},
    {"name":"peach", "r":1.0, "g":0.7, "b":0.5},
    {"name":"aqua", "r":0.0, "g":0.8, "b":0.8},
    {"name":"lime", "r":0.7, "g":1.0, "b":0.3},
    {"name":"plum", "r":0.5, "g":0.2, "b":0.5},
    {"name":"cherry", "r":0.8, "g":0.1, "b":0.2},
    {"name":"denim", "r":0.1, "g":0.3, "b":0.6},
    {"name":"mustard", "r":0.9, "g":0.7, "b":0.2},
    {"name":"coral", "r":1.0, "g":0.5, "b":0.4},
    {"name":"teal", "r":0.2, "g":0.6, "b":0.6},
    {"name":"ivory", "r":1.0, "g":1.0, "b":0.9}
]

# DataFrame으로 변환
df_palette = pd.DataFrame(palette_data)

# CSV 파일로 저장 (덮어쓰기)
df_palette.to_csv("palette.csv", index=False)
print("✅ palette.csv에 20개 색상 저장 완료")

palette_csv = load_csv_palette()
show_palette(palette_csv)